FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir \
    streamlit \
    pandas \
    psycopg2-binary \
    altair

COPY realtime/ /app/realtime/
COPY monitoring/ /app/monitoring/

WORKDIR /app/realtime

CMD ["streamlit", "run", "dashboard/streamlit_app.py", "--server.address=0.0.0.0"]
